-- Region Hierarchy Completion SQL
-- Insert statements for establishing proper region hierarchy relationships

-- These INSERT statements were generated by the query studying the regions table.
-- Note: This creates incorrect relationships linking EVERY province to EVERY town,
-- which is not realistic. In practice, we'd need proper geographic mapping.

-- For demonstration purposes, here are the sample correct relationships:

-- 1. Limpopo Province (ID: 5) to District Municipalities + Towns in Limpopo
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(5, 140, 1, 'administrative', 1),  -- Limpopo -> Waterberg DM
(5, 141, 1, 'administrative', 1),  -- Limpopo -> Capricorn DM
(5, 142, 1, 'administrative', 1),  -- Limpopo -> Polokwane
(5, 35, 1, 'administrative', 1);   -- Limpopo -> Polokwane (original)

-- 2. Mpumalanga Province (ID: 6) to Towns in Mpumalanga
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(6, 143, 1, 'administrative', 1),  -- Mpumalanga -> Nelspruit
(6, 36, 1, 'administrative', 1);   -- Mpumalanga -> Nelspruit (original)

-- 3. Northern Cape Province (ID: 8) to Towns in Northern Cape
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(8, 144, 1, 'administrative', 1),  -- Northern Cape -> Kimberley
(8, 145, 1, 'administrative', 1),  -- Northern Cape -> Upington
(8, 148, 1, 'administrative', 1),  -- Northern Cape -> Beaufort West
(8, 37, 1, 'administrative', 1),   -- Northern Cape -> Kimberley (original)
(8, 38, 1, 'administrative', 1),   -- Northern Cape -> Upington (original)
(8, 42, 1, 'administrative', 1);   -- Northern Cape -> Beaufort West (original)

-- 4. North West Province (ID: 7) to Towns in North West
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(7, 146, 1, 'administrative', 1),  -- North West -> Rustenburg
(7, 43, 1, 'administrative', 1);   -- North West -> Rustenburg (original)

-- 5. Gauteng Province (ID: 1) to Towns in Gauteng
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(1, 28, 1, 'administrative', 1),   -- Gauteng -> Johannesburg
(1, 31, 1, 'administrative', 1),   -- Gauteng -> Pretoria
(1, 45, 1, 'administrative', 1),   -- Gauteng -> Vanderbijlpark
(1, 147, 1, 'administrative', 1);  -- Gauteng -> Vanderbijlpark

-- 6. Western Cape Province (ID: 2) to Towns in Western Cape
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(2, 29, 1, 'administrative', 1),   -- Western Cape -> Cape Town
(2, 39, 1, 'administrative', 1),   -- Western Cape -> George
(2, 40, 1, 'administrative', 1),   -- Western Cape -> Oudtshoorn
(2, 41, 1, 'administrative', 1);   -- Western Cape -> Mossel Bay

-- 7. KwaZulu-Natal Province (ID: 3) to Towns in KwaZulu-Natal
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(3, 30, 1, 'administrative', 1),   -- KwaZulu-Natal -> Durban
(3, 50, 1, 'administrative', 1),   -- KwaZulu-Natal -> Pietermaritzburg
(3, 51, 1, 'administrative', 1),   -- KwaZulu-Natal -> Richards Bay
(3, 52, 1, 'administrative', 1),   -- KwaZulu-Natal -> Newcastle
(3, 53, 1, 'administrative', 1),   -- KwaZulu-Natal -> Ladysmith
(3, 54, 1, 'administrative', 1);   -- KwaZulu-Natal -> Vryheid

-- 8. Eastern Cape Province (ID: 4) to Towns in Eastern Cape
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(4, 32, 1, 'administrative', 1),   -- Eastern Cape -> Port Elizabeth
(4, 34, 1, 'administrative', 1);   -- Eastern Cape -> East London

-- 9. Free State Province (ID: 9) to Towns in Free State
INSERT INTO region_hierarchy (ancestor_id, descendant_id, path_length, hierarchy_type, is_primary_path) VALUES
(9, 33, 1, 'administrative', 1),   -- Free State -> Bloemfontein
(9, 46, 1, 'administrative', 1),   -- Free State -> Klerksdorp
(9, 47, 1, 'administrative', 1),   -- Free State -> Welkom
(9, 48, 1, 'administrative', 1),   -- Free State -> Bethlehem
(9, 49, 1, 'administrative', 1);   -- Free State -> Harrismith

COMMIT;

-- Note: The generated SQL from the earlier query linked EVERY province to EVERY town,
-- which creates incorrect geography. This corrected version only links provinces
-- to regions actually within those provinces.

-- For production use, you would need accurate geographic mapping data that
-- specifies which towns belong to which provinces.
